#############################################################################
# Makefile for building: serverDemo
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  serverDemo.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile serverDemo.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = serverDemo1.0.0
DISTDIR = /home/zxy/CS-practice/ZaunChat-main/Server/.tmp/serverDemo1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = DataBase/datadb.cpp \
		DataModel/Msg/msg.cpp \
		DataModel/chatmessage.cpp \
		DataModel/filemeta.cpp \
		DataModel/filepackage.cpp \
		DataModel/groupinfo.cpp \
		DataModel/userinfo.cpp \
		Network/Handlers/FriendshipHandler.cpp \
		Network/Handlers/LoginHandler.cpp \
		Network/Handlers/LogoutHandler.cpp \
		Network/Handlers/RegisterHandler.cpp \
		Network/Handlers/addGroupHandler.cpp \
		Network/Handlers/addfriendresulthandler.cpp \
		Network/Handlers/chatmsghandler.cpp \
		Network/Handlers/group_msg_handler.cpp \
		Network/Handlers/modifyUsernameHandler.cpp \
		Network/Handlers/modifyavatarhandler.cpp \
		Network/Handlers/offlinemsghandler.cpp \
		Network/Handlers/registerGroupHandler.cpp \
		Network/Handlers/requestAllGroupListHandler.cpp \
		Network/Handlers/requestUserInfoHandler.cpp \
		Network/Handlers/requestallfriendlisthandler.cpp \
		Network/ResAssist/localcache.cpp \
		Network/ResAssist/ressocket.cpp \
		Network/Server/resserver.cpp \
		Network/Server/server.cpp \
		Network/Server/tcpserver.cpp \
		Network/serverhandlerreg.cpp \
		Network/tcpclientsocket.cpp \
		Utilities/log.cpp \
		Utilities/qbytearraylistutility.cpp \
		main.cpp \
		servercontroller.cpp \
		widget.cpp moc_FriendshipHandler.cpp \
		moc_LoginHandler.cpp \
		moc_LogoutHandler.cpp \
		moc_RegisterHandler.cpp \
		moc_addGroupHandler.cpp \
		moc_addfriendresulthandler.cpp \
		moc_chatmsghandler.cpp \
		moc_group_msg_handler.cpp \
		moc_modifyUsernameHandler.cpp \
		moc_modifyavatarhandler.cpp \
		moc_msghandler.cpp \
		moc_offlinemsghandler.cpp \
		moc_registerGroupHandler.cpp \
		moc_requestAllGroupListHandler.cpp \
		moc_requestUserInfoHandler.cpp \
		moc_requestallfriendlisthandler.cpp \
		moc_localcache.cpp \
		moc_ressocket.cpp \
		moc_resserver.cpp \
		moc_server.cpp \
		moc_tcpserver.cpp \
		moc_serverhandlerreg.cpp \
		moc_tcpclientsocket.cpp \
		moc_log.cpp \
		moc_widget.cpp
OBJECTS       = datadb.o \
		msg.o \
		chatmessage.o \
		filemeta.o \
		filepackage.o \
		groupinfo.o \
		userinfo.o \
		FriendshipHandler.o \
		LoginHandler.o \
		LogoutHandler.o \
		RegisterHandler.o \
		addGroupHandler.o \
		addfriendresulthandler.o \
		chatmsghandler.o \
		group_msg_handler.o \
		modifyUsernameHandler.o \
		modifyavatarhandler.o \
		offlinemsghandler.o \
		registerGroupHandler.o \
		requestAllGroupListHandler.o \
		requestUserInfoHandler.o \
		requestallfriendlisthandler.o \
		localcache.o \
		ressocket.o \
		resserver.o \
		server.o \
		tcpserver.o \
		serverhandlerreg.o \
		tcpclientsocket.o \
		log.o \
		qbytearraylistutility.o \
		main.o \
		servercontroller.o \
		widget.o \
		moc_FriendshipHandler.o \
		moc_LoginHandler.o \
		moc_LogoutHandler.o \
		moc_RegisterHandler.o \
		moc_addGroupHandler.o \
		moc_addfriendresulthandler.o \
		moc_chatmsghandler.o \
		moc_group_msg_handler.o \
		moc_modifyUsernameHandler.o \
		moc_modifyavatarhandler.o \
		moc_msghandler.o \
		moc_offlinemsghandler.o \
		moc_registerGroupHandler.o \
		moc_requestAllGroupListHandler.o \
		moc_requestUserInfoHandler.o \
		moc_requestallfriendlisthandler.o \
		moc_localcache.o \
		moc_ressocket.o \
		moc_resserver.o \
		moc_server.o \
		moc_tcpserver.o \
		moc_serverhandlerreg.o \
		moc_tcpclientsocket.o \
		moc_log.o \
		moc_widget.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		serverDemo.pro DataBase/datadb.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		DataModel/groupinfo.h \
		DataModel/userinfo.h \
		Network/Handlers/FriendshipHandler.h \
		Network/Handlers/LoginHandler.h \
		Network/Handlers/LogoutHandler.h \
		Network/Handlers/RegisterHandler.h \
		Network/Handlers/addGroupHandler.h \
		Network/Handlers/addfriendresulthandler.h \
		Network/Handlers/chatmsghandler.h \
		Network/Handlers/group_msg_handler.h \
		Network/Handlers/modifyUsernameHandler.h \
		Network/Handlers/modifyavatarhandler.h \
		Network/Handlers/msghandler.h \
		Network/Handlers/offlinemsghandler.h \
		Network/Handlers/registerGroupHandler.h \
		Network/Handlers/requestAllGroupListHandler.h \
		Network/Handlers/requestUserInfoHandler.h \
		Network/Handlers/requestallfriendlisthandler.h \
		Network/ResAssist/localcache.h \
		Network/ResAssist/res.h \
		Network/ResAssist/ressocket.h \
		Network/Server/resserver.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/serverhandlerreg.h \
		Network/tcpclientsocket.h \
		Utilities/log.h \
		Utilities/qbytearraylistutility.h \
		Utilities/standarddatetimeutilities.h \
		Utilities/utilities.h \
		servercontroller.h \
		widget.h DataBase/datadb.cpp \
		DataModel/Msg/msg.cpp \
		DataModel/chatmessage.cpp \
		DataModel/filemeta.cpp \
		DataModel/filepackage.cpp \
		DataModel/groupinfo.cpp \
		DataModel/userinfo.cpp \
		Network/Handlers/FriendshipHandler.cpp \
		Network/Handlers/LoginHandler.cpp \
		Network/Handlers/LogoutHandler.cpp \
		Network/Handlers/RegisterHandler.cpp \
		Network/Handlers/addGroupHandler.cpp \
		Network/Handlers/addfriendresulthandler.cpp \
		Network/Handlers/chatmsghandler.cpp \
		Network/Handlers/group_msg_handler.cpp \
		Network/Handlers/modifyUsernameHandler.cpp \
		Network/Handlers/modifyavatarhandler.cpp \
		Network/Handlers/offlinemsghandler.cpp \
		Network/Handlers/registerGroupHandler.cpp \
		Network/Handlers/requestAllGroupListHandler.cpp \
		Network/Handlers/requestUserInfoHandler.cpp \
		Network/Handlers/requestallfriendlisthandler.cpp \
		Network/ResAssist/localcache.cpp \
		Network/ResAssist/ressocket.cpp \
		Network/Server/resserver.cpp \
		Network/Server/server.cpp \
		Network/Server/tcpserver.cpp \
		Network/serverhandlerreg.cpp \
		Network/tcpclientsocket.cpp \
		Utilities/log.cpp \
		Utilities/qbytearraylistutility.cpp \
		main.cpp \
		servercontroller.cpp \
		widget.cpp
QMAKE_TARGET  = serverDemo
DESTDIR       = 
TARGET        = serverDemo


first: all
####### Build rules

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: serverDemo.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		serverDemo.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Sql.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile serverDemo.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
serverDemo.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Sql.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile serverDemo.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents DataBase/datadb.h DataModel/Msg/msg.h DataModel/Msg/msgtype.h DataModel/chatmessage.h DataModel/datamodel.h DataModel/filemeta.h DataModel/filepackage.h DataModel/groupinfo.h DataModel/userinfo.h Network/Handlers/FriendshipHandler.h Network/Handlers/LoginHandler.h Network/Handlers/LogoutHandler.h Network/Handlers/RegisterHandler.h Network/Handlers/addGroupHandler.h Network/Handlers/addfriendresulthandler.h Network/Handlers/chatmsghandler.h Network/Handlers/group_msg_handler.h Network/Handlers/modifyUsernameHandler.h Network/Handlers/modifyavatarhandler.h Network/Handlers/msghandler.h Network/Handlers/offlinemsghandler.h Network/Handlers/registerGroupHandler.h Network/Handlers/requestAllGroupListHandler.h Network/Handlers/requestUserInfoHandler.h Network/Handlers/requestallfriendlisthandler.h Network/ResAssist/localcache.h Network/ResAssist/res.h Network/ResAssist/ressocket.h Network/Server/resserver.h Network/Server/server.h Network/Server/tcpserver.h Network/serverhandlerreg.h Network/tcpclientsocket.h Utilities/log.h Utilities/qbytearraylistutility.h Utilities/standarddatetimeutilities.h Utilities/utilities.h servercontroller.h widget.h $(DISTDIR)/
	$(COPY_FILE) --parents DataBase/datadb.cpp DataModel/Msg/msg.cpp DataModel/chatmessage.cpp DataModel/filemeta.cpp DataModel/filepackage.cpp DataModel/groupinfo.cpp DataModel/userinfo.cpp Network/Handlers/FriendshipHandler.cpp Network/Handlers/LoginHandler.cpp Network/Handlers/LogoutHandler.cpp Network/Handlers/RegisterHandler.cpp Network/Handlers/addGroupHandler.cpp Network/Handlers/addfriendresulthandler.cpp Network/Handlers/chatmsghandler.cpp Network/Handlers/group_msg_handler.cpp Network/Handlers/modifyUsernameHandler.cpp Network/Handlers/modifyavatarhandler.cpp Network/Handlers/offlinemsghandler.cpp Network/Handlers/registerGroupHandler.cpp Network/Handlers/requestAllGroupListHandler.cpp Network/Handlers/requestUserInfoHandler.cpp Network/Handlers/requestallfriendlisthandler.cpp Network/ResAssist/localcache.cpp Network/ResAssist/ressocket.cpp Network/Server/resserver.cpp Network/Server/server.cpp Network/Server/tcpserver.cpp Network/serverhandlerreg.cpp Network/tcpclientsocket.cpp Utilities/log.cpp Utilities/qbytearraylistutility.cpp main.cpp servercontroller.cpp widget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_FriendshipHandler.cpp moc_LoginHandler.cpp moc_LogoutHandler.cpp moc_RegisterHandler.cpp moc_addGroupHandler.cpp moc_addfriendresulthandler.cpp moc_chatmsghandler.cpp moc_group_msg_handler.cpp moc_modifyUsernameHandler.cpp moc_modifyavatarhandler.cpp moc_msghandler.cpp moc_offlinemsghandler.cpp moc_registerGroupHandler.cpp moc_requestAllGroupListHandler.cpp moc_requestUserInfoHandler.cpp moc_requestallfriendlisthandler.cpp moc_localcache.cpp moc_ressocket.cpp moc_resserver.cpp moc_server.cpp moc_tcpserver.cpp moc_serverhandlerreg.cpp moc_tcpclientsocket.cpp moc_log.cpp moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_FriendshipHandler.cpp moc_LoginHandler.cpp moc_LogoutHandler.cpp moc_RegisterHandler.cpp moc_addGroupHandler.cpp moc_addfriendresulthandler.cpp moc_chatmsghandler.cpp moc_group_msg_handler.cpp moc_modifyUsernameHandler.cpp moc_modifyavatarhandler.cpp moc_msghandler.cpp moc_offlinemsghandler.cpp moc_registerGroupHandler.cpp moc_requestAllGroupListHandler.cpp moc_requestUserInfoHandler.cpp moc_requestallfriendlisthandler.cpp moc_localcache.cpp moc_ressocket.cpp moc_resserver.cpp moc_server.cpp moc_tcpserver.cpp moc_serverhandlerreg.cpp moc_tcpclientsocket.cpp moc_log.cpp moc_widget.cpp
moc_FriendshipHandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/FriendshipHandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/FriendshipHandler.h -o moc_FriendshipHandler.cpp

moc_LoginHandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/LoginHandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/LoginHandler.h -o moc_LoginHandler.cpp

moc_LogoutHandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/LogoutHandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/LogoutHandler.h -o moc_LogoutHandler.cpp

moc_RegisterHandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/RegisterHandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/RegisterHandler.h -o moc_RegisterHandler.cpp

moc_addGroupHandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/addGroupHandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/addGroupHandler.h -o moc_addGroupHandler.cpp

moc_addfriendresulthandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Utilities/log.h \
		DataModel/chatmessage.h \
		DataBase/datadb.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Network/Handlers/addfriendresulthandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/addfriendresulthandler.h -o moc_addfriendresulthandler.cpp

moc_chatmsghandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		DataModel/chatmessage.h \
		Network/Handlers/chatmsghandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/chatmsghandler.h -o moc_chatmsghandler.cpp

moc_group_msg_handler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/group_msg_handler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/group_msg_handler.h -o moc_group_msg_handler.cpp

moc_modifyUsernameHandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/modifyUsernameHandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/modifyUsernameHandler.h -o moc_modifyUsernameHandler.cpp

moc_modifyavatarhandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/modifyavatarhandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/modifyavatarhandler.h -o moc_modifyavatarhandler.cpp

moc_msghandler.cpp: DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/msghandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/msghandler.h -o moc_msghandler.cpp

moc_offlinemsghandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/offlinemsghandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/offlinemsghandler.h -o moc_offlinemsghandler.cpp

moc_registerGroupHandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/registerGroupHandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/registerGroupHandler.h -o moc_registerGroupHandler.cpp

moc_requestAllGroupListHandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/requestAllGroupListHandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/requestAllGroupListHandler.h -o moc_requestAllGroupListHandler.cpp

moc_requestUserInfoHandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/requestUserInfoHandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/requestUserInfoHandler.h -o moc_requestUserInfoHandler.cpp

moc_requestallfriendlisthandler.cpp: Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Network/Handlers/requestallfriendlisthandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Handlers/requestallfriendlisthandler.h -o moc_requestallfriendlisthandler.cpp

moc_localcache.cpp: DataModel/datamodel.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		DataModel/chatmessage.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		Network/ResAssist/localcache.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/ResAssist/localcache.h -o moc_localcache.cpp

moc_ressocket.cpp: Network/tcpclientsocket.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		DataModel/datamodel.h \
		DataModel/chatmessage.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		Network/ResAssist/ressocket.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/ResAssist/ressocket.h -o moc_ressocket.cpp

moc_resserver.cpp: Network/tcpclientsocket.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Server/resserver.h -o moc_resserver.cpp

moc_server.cpp: Network/tcpclientsocket.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/Server/tcpserver.h \
		Network/Server/server.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Server/server.h -o moc_server.cpp

moc_tcpserver.cpp: Network/Server/tcpserver.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/Server/tcpserver.h -o moc_tcpserver.cpp

moc_serverhandlerreg.cpp: DataModel/Msg/msgtype.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		Network/tcpclientsocket.h \
		Network/Handlers/RegisterHandler.h \
		Network/Handlers/LoginHandler.h \
		Network/Handlers/chatmsghandler.h \
		DataModel/chatmessage.h \
		Network/Handlers/FriendshipHandler.h \
		Network/Handlers/requestallfriendlisthandler.h \
		Network/Handlers/addfriendresulthandler.h \
		Utilities/log.h \
		DataBase/datadb.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Network/Handlers/LogoutHandler.h \
		Network/Handlers/requestUserInfoHandler.h \
		Network/Handlers/offlinemsghandler.h \
		Network/Handlers/registerGroupHandler.h \
		Network/Handlers/modifyUsernameHandler.h \
		Network/Handlers/addGroupHandler.h \
		Network/Handlers/requestAllGroupListHandler.h \
		Network/Handlers/group_msg_handler.h \
		Network/Handlers/modifyavatarhandler.h \
		Network/serverhandlerreg.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/serverhandlerreg.h -o moc_serverhandlerreg.cpp

moc_tcpclientsocket.cpp: DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/tcpclientsocket.h -o moc_tcpclientsocket.cpp

moc_log.cpp: Utilities/log.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Utilities/log.h -o moc_log.cpp

moc_widget.cpp: widget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/zxy/CS-practice/ZaunChat-main/Server -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include widget.h -o moc_widget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

datadb.o: DataBase/datadb.cpp DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		Utilities/utilities.h \
		Utilities/log.h \
		Utilities/standarddatetimeutilities.h \
		Utilities/qbytearraylistutility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datadb.o DataBase/datadb.cpp

msg.o: DataModel/Msg/msg.cpp DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o msg.o DataModel/Msg/msg.cpp

chatmessage.o: DataModel/chatmessage.cpp DataModel/chatmessage.h \
		Utilities/standarddatetimeutilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chatmessage.o DataModel/chatmessage.cpp

filemeta.o: DataModel/filemeta.cpp DataModel/filemeta.h \
		DataModel/userinfo.h \
		Utilities/utilities.h \
		Utilities/log.h \
		Utilities/standarddatetimeutilities.h \
		Utilities/qbytearraylistutility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filemeta.o DataModel/filemeta.cpp

filepackage.o: DataModel/filepackage.cpp DataModel/filepackage.h \
		DataModel/filemeta.h \
		DataModel/userinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filepackage.o DataModel/filepackage.cpp

groupinfo.o: DataModel/groupinfo.cpp DataModel/groupinfo.h \
		DataModel/userinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o groupinfo.o DataModel/groupinfo.cpp

userinfo.o: DataModel/userinfo.cpp DataModel/userinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userinfo.o DataModel/userinfo.cpp

FriendshipHandler.o: Network/Handlers/FriendshipHandler.cpp Network/Handlers/FriendshipHandler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Utilities/log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FriendshipHandler.o Network/Handlers/FriendshipHandler.cpp

LoginHandler.o: Network/Handlers/LoginHandler.cpp DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		Network/Handlers/LoginHandler.h \
		Network/Handlers/msghandler.h \
		Network/tcpclientsocket.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Utilities/utilities.h \
		Utilities/log.h \
		Utilities/standarddatetimeutilities.h \
		Utilities/qbytearraylistutility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoginHandler.o Network/Handlers/LoginHandler.cpp

LogoutHandler.o: Network/Handlers/LogoutHandler.cpp DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		Network/Handlers/LogoutHandler.h \
		Network/Handlers/msghandler.h \
		Network/tcpclientsocket.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Utilities/utilities.h \
		Utilities/log.h \
		Utilities/standarddatetimeutilities.h \
		Utilities/qbytearraylistutility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LogoutHandler.o Network/Handlers/LogoutHandler.cpp

RegisterHandler.o: Network/Handlers/RegisterHandler.cpp Network/Handlers/RegisterHandler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		Utilities/log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RegisterHandler.o Network/Handlers/RegisterHandler.cpp

addGroupHandler.o: Network/Handlers/addGroupHandler.cpp Network/Handlers/addGroupHandler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Utilities/log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addGroupHandler.o Network/Handlers/addGroupHandler.cpp

addfriendresulthandler.o: Network/Handlers/addfriendresulthandler.cpp Network/Handlers/addfriendresulthandler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Utilities/log.h \
		DataModel/chatmessage.h \
		DataBase/datadb.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addfriendresulthandler.o Network/Handlers/addfriendresulthandler.cpp

chatmsghandler.o: Network/Handlers/chatmsghandler.cpp Network/Handlers/chatmsghandler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		DataModel/chatmessage.h \
		DataBase/datadb.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Utilities/log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chatmsghandler.o Network/Handlers/chatmsghandler.cpp

group_msg_handler.o: Network/Handlers/group_msg_handler.cpp Network/Handlers/group_msg_handler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		DataModel/chatmessage.h \
		DataBase/datadb.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Utilities/utilities.h \
		Utilities/log.h \
		Utilities/standarddatetimeutilities.h \
		Utilities/qbytearraylistutility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o group_msg_handler.o Network/Handlers/group_msg_handler.cpp

modifyUsernameHandler.o: Network/Handlers/modifyUsernameHandler.cpp Network/Handlers/modifyUsernameHandler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Utilities/log.h \
		DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modifyUsernameHandler.o Network/Handlers/modifyUsernameHandler.cpp

modifyavatarhandler.o: Network/Handlers/modifyavatarhandler.cpp Network/Handlers/modifyavatarhandler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Utilities/utilities.h \
		Utilities/log.h \
		Utilities/standarddatetimeutilities.h \
		Utilities/qbytearraylistutility.h \
		DataModel/datamodel.h \
		DataModel/chatmessage.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		DataBase/datadb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modifyavatarhandler.o Network/Handlers/modifyavatarhandler.cpp

offlinemsghandler.o: Network/Handlers/offlinemsghandler.cpp Network/Handlers/offlinemsghandler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Utilities/log.h \
		DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o offlinemsghandler.o Network/Handlers/offlinemsghandler.cpp

registerGroupHandler.o: Network/Handlers/registerGroupHandler.cpp Network/Handlers/registerGroupHandler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		Utilities/log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registerGroupHandler.o Network/Handlers/registerGroupHandler.cpp

requestAllGroupListHandler.o: Network/Handlers/requestAllGroupListHandler.cpp Network/Handlers/requestAllGroupListHandler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Utilities/log.h \
		DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		Utilities/qbytearraylistutility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o requestAllGroupListHandler.o Network/Handlers/requestAllGroupListHandler.cpp

requestUserInfoHandler.o: Network/Handlers/requestUserInfoHandler.cpp Network/Handlers/requestUserInfoHandler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		Utilities/log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o requestUserInfoHandler.o Network/Handlers/requestUserInfoHandler.cpp

requestallfriendlisthandler.o: Network/Handlers/requestallfriendlisthandler.cpp Network/Handlers/requestallfriendlisthandler.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/tcpclientsocket.h \
		Utilities/log.h \
		DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		Utilities/qbytearraylistutility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o requestallfriendlisthandler.o Network/Handlers/requestallfriendlisthandler.cpp

localcache.o: Network/ResAssist/localcache.cpp Network/ResAssist/localcache.h \
		DataModel/datamodel.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		DataModel/chatmessage.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o localcache.o Network/ResAssist/localcache.cpp

ressocket.o: Network/ResAssist/ressocket.cpp Network/ResAssist/ressocket.h \
		Network/tcpclientsocket.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		DataModel/datamodel.h \
		DataModel/chatmessage.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		Utilities/log.h \
		Network/ResAssist/localcache.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ressocket.o Network/ResAssist/ressocket.cpp

resserver.o: Network/Server/resserver.cpp Network/Server/resserver.h \
		Network/tcpclientsocket.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/Server/tcpserver.h \
		Utilities/log.h \
		Network/ResAssist/ressocket.h \
		DataModel/datamodel.h \
		DataModel/chatmessage.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resserver.o Network/Server/resserver.cpp

server.o: Network/Server/server.cpp Network/Server/server.h \
		Network/tcpclientsocket.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/Server/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o server.o Network/Server/server.cpp

tcpserver.o: Network/Server/tcpserver.cpp Network/Server/tcpserver.h \
		Network/tcpclientsocket.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/Server/server.h \
		servercontroller.h \
		Network/Server/resserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpserver.o Network/Server/tcpserver.cpp

serverhandlerreg.o: Network/serverhandlerreg.cpp Network/serverhandlerreg.h \
		DataModel/Msg/msgtype.h \
		Network/Handlers/msghandler.h \
		DataModel/Msg/msg.h \
		Network/tcpclientsocket.h \
		Network/Handlers/RegisterHandler.h \
		Network/Handlers/LoginHandler.h \
		Network/Handlers/chatmsghandler.h \
		DataModel/chatmessage.h \
		Network/Handlers/FriendshipHandler.h \
		Network/Handlers/requestallfriendlisthandler.h \
		Network/Handlers/addfriendresulthandler.h \
		Utilities/log.h \
		DataBase/datadb.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Network/Handlers/LogoutHandler.h \
		Network/Handlers/requestUserInfoHandler.h \
		Network/Handlers/offlinemsghandler.h \
		Network/Handlers/registerGroupHandler.h \
		Network/Handlers/modifyUsernameHandler.h \
		Network/Handlers/addGroupHandler.h \
		Network/Handlers/requestAllGroupListHandler.h \
		Network/Handlers/group_msg_handler.h \
		Network/Handlers/modifyavatarhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serverhandlerreg.o Network/serverhandlerreg.cpp

tcpclientsocket.o: Network/tcpclientsocket.cpp Network/tcpclientsocket.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/serverhandlerreg.h \
		Network/Handlers/msghandler.h \
		Network/Handlers/RegisterHandler.h \
		Network/Handlers/LoginHandler.h \
		Network/Handlers/chatmsghandler.h \
		DataModel/chatmessage.h \
		Network/Handlers/FriendshipHandler.h \
		Network/Handlers/requestallfriendlisthandler.h \
		Network/Handlers/addfriendresulthandler.h \
		Utilities/log.h \
		DataBase/datadb.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Network/Handlers/LogoutHandler.h \
		Network/Handlers/requestUserInfoHandler.h \
		Network/Handlers/offlinemsghandler.h \
		Network/Handlers/registerGroupHandler.h \
		Network/Handlers/modifyUsernameHandler.h \
		Network/Handlers/addGroupHandler.h \
		Network/Handlers/requestAllGroupListHandler.h \
		Network/Handlers/group_msg_handler.h \
		Network/Handlers/modifyavatarhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpclientsocket.o Network/tcpclientsocket.cpp

log.o: Utilities/log.cpp Utilities/log.h \
		Utilities/utilities.h \
		Utilities/standarddatetimeutilities.h \
		Utilities/qbytearraylistutility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o log.o Utilities/log.cpp

qbytearraylistutility.o: Utilities/qbytearraylistutility.cpp Utilities/qbytearraylistutility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbytearraylistutility.o Utilities/qbytearraylistutility.cpp

main.o: main.cpp widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

servercontroller.o: servercontroller.cpp servercontroller.h \
		Network/Server/server.h \
		Network/tcpclientsocket.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o servercontroller.o servercontroller.cpp

widget.o: widget.cpp widget.h \
		ui_widget.h \
		servercontroller.h \
		Network/Server/server.h \
		Network/tcpclientsocket.h \
		DataModel/Msg/msg.h \
		DataModel/Msg/msgtype.h \
		Network/Server/tcpserver.h \
		Network/Server/resserver.h \
		Utilities/utilities.h \
		Utilities/log.h \
		Utilities/standarddatetimeutilities.h \
		Utilities/qbytearraylistutility.h \
		DataBase/datadb.h \
		DataModel/chatmessage.h \
		DataModel/datamodel.h \
		DataModel/userinfo.h \
		DataModel/groupinfo.h \
		DataModel/filemeta.h \
		DataModel/filepackage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

moc_FriendshipHandler.o: moc_FriendshipHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FriendshipHandler.o moc_FriendshipHandler.cpp

moc_LoginHandler.o: moc_LoginHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LoginHandler.o moc_LoginHandler.cpp

moc_LogoutHandler.o: moc_LogoutHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LogoutHandler.o moc_LogoutHandler.cpp

moc_RegisterHandler.o: moc_RegisterHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RegisterHandler.o moc_RegisterHandler.cpp

moc_addGroupHandler.o: moc_addGroupHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addGroupHandler.o moc_addGroupHandler.cpp

moc_addfriendresulthandler.o: moc_addfriendresulthandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addfriendresulthandler.o moc_addfriendresulthandler.cpp

moc_chatmsghandler.o: moc_chatmsghandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chatmsghandler.o moc_chatmsghandler.cpp

moc_group_msg_handler.o: moc_group_msg_handler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_group_msg_handler.o moc_group_msg_handler.cpp

moc_modifyUsernameHandler.o: moc_modifyUsernameHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modifyUsernameHandler.o moc_modifyUsernameHandler.cpp

moc_modifyavatarhandler.o: moc_modifyavatarhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modifyavatarhandler.o moc_modifyavatarhandler.cpp

moc_msghandler.o: moc_msghandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_msghandler.o moc_msghandler.cpp

moc_offlinemsghandler.o: moc_offlinemsghandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_offlinemsghandler.o moc_offlinemsghandler.cpp

moc_registerGroupHandler.o: moc_registerGroupHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registerGroupHandler.o moc_registerGroupHandler.cpp

moc_requestAllGroupListHandler.o: moc_requestAllGroupListHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_requestAllGroupListHandler.o moc_requestAllGroupListHandler.cpp

moc_requestUserInfoHandler.o: moc_requestUserInfoHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_requestUserInfoHandler.o moc_requestUserInfoHandler.cpp

moc_requestallfriendlisthandler.o: moc_requestallfriendlisthandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_requestallfriendlisthandler.o moc_requestallfriendlisthandler.cpp

moc_localcache.o: moc_localcache.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_localcache.o moc_localcache.cpp

moc_ressocket.o: moc_ressocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ressocket.o moc_ressocket.cpp

moc_resserver.o: moc_resserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_resserver.o moc_resserver.cpp

moc_server.o: moc_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_server.o moc_server.cpp

moc_tcpserver.o: moc_tcpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpserver.o moc_tcpserver.cpp

moc_serverhandlerreg.o: moc_serverhandlerreg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serverhandlerreg.o moc_serverhandlerreg.cpp

moc_tcpclientsocket.o: moc_tcpclientsocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpclientsocket.o moc_tcpclientsocket.cpp

moc_log.o: moc_log.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_log.o moc_log.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/serverDemo/bin || mkdir -p $(INSTALL_ROOT)/opt/serverDemo/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/serverDemo/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/serverDemo/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/serverDemo/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/serverDemo/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

